module LocationsHelper
  def self.dioceses_options
    ["Bangor",
    "Canterbury",
    "Carlisle",
    "Chester",
    "Chichester",
    "Durham",
    "Ely",
    "Exeter",
    "Lincoln",
    "Llandaff",
    "London",
    "Hereford",
    "Norwich",
    "Rochester",
    "Salisbury",
    "St. Asaph's",
    "St. David's",
    "Wells",
    "Winchester",
    "Worcester",
    "York"]
  end
  
  def self.english_county_options
    ["Bedfordshire",
    "Berkshire",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "Cornwall",
    "Cumberland",
    "Derbyshire",
    "Devon",
    "Dorset",
    "Durham",
    "Essex",
    "Gloucestershire",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Huntingtonshire",
    "Kent",
    "Lancashire",
    "Middlesex",
    "Norfolk",
    "Northingamptonshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Some of Peterborough",
    "Somerset",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Warwickshire",
    "Westmorland",
    "Wiltshire",
    "Worcestershire",
    "Yorkshire"]
  end
  
  def self.buildings_of_england_volume_options
    ["Bedfordshire",
    "Berkshire",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "Cornwall",
    "Cumberland",
    "Derbyshire",
    "Devon",
    "Dorset",
    "Durham",
    "Essex",
    "Gloucestershire",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Huntingtonshire",
    "Kent",
    "Lancashire",
    "Middlesex",
    "Norfolk",
    "Northingamptonshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Some of Peterborough",
    "Somerset",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Warwickshire",
    "Westmorland",
    "Wiltshire",
    "Worcestershire",
    "Yorkshire",
    "Sussex: East with Brighton and Hove",
    "Warwickshire", 
    "Wiltshire", 
    "Yorkshire: York and the East Riding",
    "Yorkshire: The North Riding", 
    "Yorkshire West Riding: Leeds, Bradford and the North"]
  end
end
